/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulo_regTramite;

import crud.Conexion;
import java.util.ArrayList;
import javax.swing.JCheckBox;

/**
 *
 * @author kid_d_000
 */
public class Prueba extends javax.swing.JFrame {

    Conexion c;
    ArrayList<JCheckBox> box;

    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
        ArrayList<String> lista = new ArrayList<String>();
        box = new ArrayList<JCheckBox>();
        c = new Conexion();
        c.conectar();
        lista = Conexion.llenar_combo();
        for (int i = 0; i < lista.size(); i++) {
            jComboBox1.addItem(lista.get(i));
        }
        box.add(guion);
        box.add(dibEsc);
        box.add(fotColIn);
        box.add(docProp);
        box.add(idOfic);
        box.add(justIdi);
        box.add(docRLeg);
        box.add(planMonum);
        box.add(planDet);
        box.add(memDesc);
        box.add(regResp);
        box.add(alinea);
        box.add(constSue);
        box.add(planoTop);
        box.add(cuadConst);
        box.add(infGraf);
        box.add(docExt);
        box.add(carPod);
        box.add(planoPlan);
        box.add(fotPred);
        box.add(proyFir);
        box.add(cedRest);
        box.add(fichCurr);

        Thread hilo = new Proceso(box, jRadioButton2, jRadioButton1);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        guion = new javax.swing.JCheckBox();
        fotColIn = new javax.swing.JCheckBox();
        docProp = new javax.swing.JCheckBox();
        docRLeg = new javax.swing.JCheckBox();
        planMonum = new javax.swing.JCheckBox();
        planDet = new javax.swing.JCheckBox();
        memDesc = new javax.swing.JCheckBox();
        idOfic = new javax.swing.JCheckBox();
        justIdi = new javax.swing.JCheckBox();
        regResp = new javax.swing.JCheckBox();
        cuadConst = new javax.swing.JCheckBox();
        docExt = new javax.swing.JCheckBox();
        infGraf = new javax.swing.JCheckBox();
        alinea = new javax.swing.JCheckBox();
        constSue = new javax.swing.JCheckBox();
        planoTop = new javax.swing.JCheckBox();
        proyFir = new javax.swing.JCheckBox();
        fichCurr = new javax.swing.JCheckBox();
        cedRest = new javax.swing.JCheckBox();
        carPod = new javax.swing.JCheckBox();
        fotPred = new javax.swing.JCheckBox();
        planoPlan = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dibEsc = new javax.swing.JCheckBox();
        rSDateChooser1 = new rojeru_san.componentes.RSDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un municipio..." }));

        jLabel1.setText("Municipio");

        jLabel2.setText("Localidad");

        jLabel3.setText("Clave Trámite");

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(227, 227, 227));
        jTextField2.setText("INAH-01-001");

        jLabel4.setText("Fecha de recepción");

        jLabel5.setText("Estado del trámite:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Pendiente");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Aceptado");

        jLabel6.setText("- Documentación soporte para cada tipo de trámite -");

        guion.setText("Guion");
        guion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fotColIn.setText("Fotografía Color Inmueble");
        fotColIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        docProp.setText("Documentación Propiedad");

        docRLeg.setText("Documentación R Legal");
        docRLeg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        planMonum.setText("Planos Monumento");

        planDet.setText("Planos Detalles");
        planDet.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        memDesc.setText("Memoria Descriptiva");

        idOfic.setText("Ide Oficial");
        idOfic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        justIdi.setText("Justificación Idioma");

        regResp.setText("Registro Responsable");
        regResp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cuadConst.setText("Cuadro Const");

        docExt.setText("Documentación Extranjero");

        infGraf.setText("Inf Gráfica");
        infGraf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        alinea.setText("Alineamiento");
        alinea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        constSue.setText("Constancia Suelo");

        planoTop.setText("Plano Topográfico");
        planoTop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        proyFir.setText("Proyecto Firmado");

        fichCurr.setText("Fichas Curriculares");

        cedRest.setText("Cédula Restaurador");
        cedRest.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        carPod.setText("Carta Poder");
        carPod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fotPred.setText("Fotos Predio");
        fotPred.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        planoPlan.setText("Plano Planta");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel7.setText("Observaciones:");

        jButton1.setText("Registrar Trámite");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dibEsc.setText("Dibujo Escala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField1)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rSDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(guion)
                                .addComponent(docProp)
                                .addComponent(fotColIn)
                                .addComponent(justIdi)
                                .addComponent(idOfic)
                                .addComponent(dibEsc))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(planMonum)
                                .addComponent(docRLeg)
                                .addComponent(memDesc)
                                .addComponent(planDet)
                                .addComponent(regResp)
                                .addComponent(alinea))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(carPod)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(constSue)
                                        .addComponent(cuadConst)
                                        .addComponent(planoTop)
                                        .addComponent(docExt)
                                        .addComponent(infGraf))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(proyFir)
                                        .addComponent(fotPred)
                                        .addComponent(fichCurr)
                                        .addComponent(cedRest)
                                        .addComponent(planoPlan)))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dibEsc)
                                .addGap(3, 3, 3)
                                .addComponent(fotColIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(docProp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idOfic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(justIdi)
                                    .addComponent(alinea)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(docRLeg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(planMonum)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(planDet)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(memDesc)
                                    .addGap(52, 52, 52))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(regResp)
                                    .addGap(26, 26, 26)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infGraf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(docExt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cedRest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fichCurr))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(constSue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(planoTop)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cuadConst))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(planoPlan)
                                        .addGap(3, 3, 3)
                                        .addComponent(fotPred)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(proyFir)))
                                .addGap(52, 52, 52)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carPod)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.sql.Date date = new java.sql.Date(rSDateChooser1.getDatoFecha().getTime());

        Conexion.insertar(jComboBox1.getSelectedIndex(), jTextField2.getText(), jComboBox1.getSelectedItem().toString(),
                jTextField1.getText(), date, jRadioButton2.isSelected(), box, jTextArea1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alinea;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox carPod;
    private javax.swing.JCheckBox cedRest;
    private javax.swing.JCheckBox constSue;
    private javax.swing.JCheckBox cuadConst;
    private javax.swing.JCheckBox dibEsc;
    private javax.swing.JCheckBox docExt;
    private javax.swing.JCheckBox docProp;
    private javax.swing.JCheckBox docRLeg;
    private javax.swing.JCheckBox fichCurr;
    private javax.swing.JCheckBox fotColIn;
    private javax.swing.JCheckBox fotPred;
    private javax.swing.JCheckBox guion;
    private javax.swing.JCheckBox idOfic;
    private javax.swing.JCheckBox infGraf;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JCheckBox justIdi;
    private javax.swing.JCheckBox memDesc;
    private javax.swing.JCheckBox planDet;
    private javax.swing.JCheckBox planMonum;
    private javax.swing.JCheckBox planoPlan;
    private javax.swing.JCheckBox planoTop;
    private javax.swing.JCheckBox proyFir;
    private rojeru_san.componentes.RSDateChooser rSDateChooser1;
    private javax.swing.JCheckBox regResp;
    // End of variables declaration//GEN-END:variables
}
