/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sinahmax;

import java.awt.Color;

/**
 *
 * @author chiva
 */
public class INAH02001 extends javax.swing.JFrame {

    /**
     * Creates new form INAH02001
     */
    public INAH02001() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SolicitudParaAutorizacionDe = new javax.swing.ButtonGroup();
        TipoDeInmueble = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlFecha = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlHomoclave = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtVentanilla = new javax.swing.JTextField();
        pnlVentanilla = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlExpediente = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtHomoclave = new javax.swing.JTextField();
        txtExpediente = new javax.swing.JTextField();
        txtCentro = new javax.swing.JTextField();
        pnlSolicitudAutorizacion = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        rbOtro = new javax.swing.JRadioButton();
        rbAnuncio = new javax.swing.JRadioButton();
        rbToldo = new javax.swing.JRadioButton();
        rdAntena = new javax.swing.JRadioButton();
        pnlCodigoP = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        rbMonumento = new javax.swing.JRadioButton();
        rbZona = new javax.swing.JRadioButton();
        rbColindante = new javax.swing.JRadioButton();
        pnlTipoInmueble = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtCodigoP = new javax.swing.JTextField();
        pnlUbicacionDel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnlCalle = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        pnlNumExt = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtNumExt = new javax.swing.JTextField();
        pnlNumInt = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtNumInt = new javax.swing.JTextField();
        pnlColonia = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        pnlLocalidad = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtLocalidad = new javax.swing.JTextField();
        pnlMunicipio = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        pnlZonaDe = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtZonaDeMunicipios = new javax.swing.JTextField();
        lblInformacion = new javax.swing.JLabel();
        lblSig = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("históricos, INAH-02-001");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 430, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Autorización para colocar anuncios, toldos y/o");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("antenas en monumentos históricos, en inmuebles");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 430, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setText("colindantes con estos o en zona de monumentos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 430, 30));

        pnlFecha.setBackground(new java.awt.Color(57, 60, 62));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha de recepcion");

        javax.swing.GroupLayout pnlFechaLayout = new javax.swing.GroupLayout(pnlFecha);
        pnlFecha.setLayout(pnlFechaLayout);
        pnlFechaLayout.setHorizontalGroup(
            pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechaLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFechaLayout.setVerticalGroup(
            pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFechaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 180, 30));

        pnlHomoclave.setBackground(new java.awt.Color(57, 60, 62));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Homoclave del formato");

        javax.swing.GroupLayout pnlHomoclaveLayout = new javax.swing.GroupLayout(pnlHomoclave);
        pnlHomoclave.setLayout(pnlHomoclaveLayout);
        pnlHomoclaveLayout.setHorizontalGroup(
            pnlHomoclaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        pnlHomoclaveLayout.setVerticalGroup(
            pnlHomoclaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHomoclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 30));

        txtFecha.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 180, 30));

        txtVentanilla.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtVentanilla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVentanilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtVentanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 130, 30));

        pnlVentanilla.setBackground(new java.awt.Color(57, 60, 62));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ventanilla Nº");

        javax.swing.GroupLayout pnlVentanillaLayout = new javax.swing.GroupLayout(pnlVentanilla);
        pnlVentanilla.setLayout(pnlVentanillaLayout);
        pnlVentanillaLayout.setHorizontalGroup(
            pnlVentanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlVentanillaLayout.setVerticalGroup(
            pnlVentanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVentanillaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlVentanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 130, 30));

        pnlExpediente.setBackground(new java.awt.Color(57, 60, 62));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Expediente Nº");

        javax.swing.GroupLayout pnlExpedienteLayout = new javax.swing.GroupLayout(pnlExpediente);
        pnlExpediente.setLayout(pnlExpedienteLayout);
        pnlExpedienteLayout.setHorizontalGroup(
            pnlExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlExpedienteLayout.setVerticalGroup(
            pnlExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExpedienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 30));

        pnlCentro.setBackground(new java.awt.Color(57, 60, 62));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Centro INAH");

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, 30));

        txtHomoclave.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtHomoclave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHomoclave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtHomoclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 30));

        txtExpediente.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtExpediente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExpediente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 30));

        txtCentro.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtCentro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 130, 30));

        pnlSolicitudAutorizacion.setBackground(new java.awt.Color(57, 60, 62));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Solicitud para autorización de");

        javax.swing.GroupLayout pnlSolicitudAutorizacionLayout = new javax.swing.GroupLayout(pnlSolicitudAutorizacion);
        pnlSolicitudAutorizacion.setLayout(pnlSolicitudAutorizacionLayout);
        pnlSolicitudAutorizacionLayout.setHorizontalGroup(
            pnlSolicitudAutorizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        pnlSolicitudAutorizacionLayout.setVerticalGroup(
            pnlSolicitudAutorizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitudAutorizacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlSolicitudAutorizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 410, 30));

        rbOtro.setBackground(new java.awt.Color(255, 255, 255));
        SolicitudParaAutorizacionDe.add(rbOtro);
        rbOtro.setText("Otro");
        getContentPane().add(rbOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 100, 30));

        rbAnuncio.setBackground(new java.awt.Color(255, 255, 255));
        SolicitudParaAutorizacionDe.add(rbAnuncio);
        rbAnuncio.setText("Anuncio");
        getContentPane().add(rbAnuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, 30));

        rbToldo.setBackground(new java.awt.Color(255, 255, 255));
        SolicitudParaAutorizacionDe.add(rbToldo);
        rbToldo.setText("Toldo");
        getContentPane().add(rbToldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 100, 30));

        rdAntena.setBackground(new java.awt.Color(255, 255, 255));
        SolicitudParaAutorizacionDe.add(rdAntena);
        rdAntena.setText("Antena");
        getContentPane().add(rdAntena, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 100, 30));

        pnlCodigoP.setBackground(new java.awt.Color(57, 60, 62));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Codigo Postal:");

        javax.swing.GroupLayout pnlCodigoPLayout = new javax.swing.GroupLayout(pnlCodigoP);
        pnlCodigoP.setLayout(pnlCodigoPLayout);
        pnlCodigoPLayout.setHorizontalGroup(
            pnlCodigoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodigoPLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCodigoPLayout.setVerticalGroup(
            pnlCodigoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCodigoPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 70, 30));

        rbMonumento.setBackground(new java.awt.Color(255, 255, 255));
        TipoDeInmueble.add(rbMonumento);
        rbMonumento.setText("Monumento Historico");
        getContentPane().add(rbMonumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 130, 30));

        rbZona.setBackground(new java.awt.Color(255, 255, 255));
        TipoDeInmueble.add(rbZona);
        rbZona.setText("En Zona de mon. hist.");
        getContentPane().add(rbZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, 30));

        rbColindante.setBackground(new java.awt.Color(255, 255, 255));
        TipoDeInmueble.add(rbColindante);
        rbColindante.setText("Colindante a mon. hist");
        getContentPane().add(rbColindante, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 140, 30));

        pnlTipoInmueble.setBackground(new java.awt.Color(57, 60, 62));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tipo de inmueble");

        javax.swing.GroupLayout pnlTipoInmuebleLayout = new javax.swing.GroupLayout(pnlTipoInmueble);
        pnlTipoInmueble.setLayout(pnlTipoInmuebleLayout);
        pnlTipoInmuebleLayout.setHorizontalGroup(
            pnlTipoInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        pnlTipoInmuebleLayout.setVerticalGroup(
            pnlTipoInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTipoInmuebleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlTipoInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 410, 30));

        txtCodigoP.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtCodigoP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 110, 30));

        pnlUbicacionDel.setBackground(new java.awt.Color(57, 60, 62));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Ubicación del anuncio, toldo o antena");

        javax.swing.GroupLayout pnlUbicacionDelLayout = new javax.swing.GroupLayout(pnlUbicacionDel);
        pnlUbicacionDel.setLayout(pnlUbicacionDelLayout);
        pnlUbicacionDelLayout.setHorizontalGroup(
            pnlUbicacionDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        pnlUbicacionDelLayout.setVerticalGroup(
            pnlUbicacionDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUbicacionDelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlUbicacionDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 410, 30));

        pnlCalle.setBackground(new java.awt.Color(57, 60, 62));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Calle:");

        javax.swing.GroupLayout pnlCalleLayout = new javax.swing.GroupLayout(pnlCalle);
        pnlCalle.setLayout(pnlCalleLayout);
        pnlCalleLayout.setHorizontalGroup(
            pnlCalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalleLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCalleLayout.setVerticalGroup(
            pnlCalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCalleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 30, 30));

        txtCalle.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtCalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 200, 30));

        pnlNumExt.setBackground(new java.awt.Color(57, 60, 62));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Num Ext.");

        javax.swing.GroupLayout pnlNumExtLayout = new javax.swing.GroupLayout(pnlNumExt);
        pnlNumExt.setLayout(pnlNumExtLayout);
        pnlNumExtLayout.setHorizontalGroup(
            pnlNumExtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlNumExtLayout.setVerticalGroup(
            pnlNumExtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNumExtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlNumExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 50, 30));

        txtNumExt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtNumExt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtNumExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 40, 30));

        pnlNumInt.setBackground(new java.awt.Color(57, 60, 62));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Num Int.");

        javax.swing.GroupLayout pnlNumIntLayout = new javax.swing.GroupLayout(pnlNumInt);
        pnlNumInt.setLayout(pnlNumIntLayout);
        pnlNumIntLayout.setHorizontalGroup(
            pnlNumIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlNumIntLayout.setVerticalGroup(
            pnlNumIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNumIntLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlNumInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 50, 30));

        txtNumInt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtNumInt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtNumInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 40, 30));

        pnlColonia.setBackground(new java.awt.Color(57, 60, 62));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Colonia:");

        javax.swing.GroupLayout pnlColoniaLayout = new javax.swing.GroupLayout(pnlColonia);
        pnlColonia.setLayout(pnlColoniaLayout);
        pnlColoniaLayout.setHorizontalGroup(
            pnlColoniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColoniaLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlColoniaLayout.setVerticalGroup(
            pnlColoniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlColoniaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 40, 30));

        txtColonia.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtColonia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 190, 30));

        pnlLocalidad.setBackground(new java.awt.Color(57, 60, 62));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Localidad:");

        javax.swing.GroupLayout pnlLocalidadLayout = new javax.swing.GroupLayout(pnlLocalidad);
        pnlLocalidad.setLayout(pnlLocalidadLayout);
        pnlLocalidadLayout.setHorizontalGroup(
            pnlLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        pnlLocalidadLayout.setVerticalGroup(
            pnlLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLocalidadLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 60, 30));

        txtLocalidad.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtLocalidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 150, 30));

        pnlMunicipio.setBackground(new java.awt.Color(57, 60, 62));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Municipio:");

        javax.swing.GroupLayout pnlMunicipioLayout = new javax.swing.GroupLayout(pnlMunicipio);
        pnlMunicipio.setLayout(pnlMunicipioLayout);
        pnlMunicipioLayout.setHorizontalGroup(
            pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        pnlMunicipioLayout.setVerticalGroup(
            pnlMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMunicipioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 60, 30));

        txtMunicipio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtMunicipio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 140, 30));

        pnlZonaDe.setBackground(new java.awt.Color(57, 60, 62));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Zona de municipios historicos:");

        javax.swing.GroupLayout pnlZonaDeLayout = new javax.swing.GroupLayout(pnlZonaDe);
        pnlZonaDe.setLayout(pnlZonaDeLayout);
        pnlZonaDeLayout.setHorizontalGroup(
            pnlZonaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZonaDeLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlZonaDeLayout.setVerticalGroup(
            pnlZonaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlZonaDeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlZonaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 150, 30));

        txtZonaDeMunicipios.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtZonaDeMunicipios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtZonaDeMunicipios, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 260, 30));

        lblInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ayuda.png"))); // NOI18N
        getContentPane().add(lblInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, -1, -1));

        lblSig.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblSig.setText(">");
        lblSig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSigMouseClicked(evt);
            }
        });
        getContentPane().add(lblSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, -1, -1));

        setSize(new java.awt.Dimension(450, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        RegTramMonHis r = new RegTramMonHis();
        r.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lblSigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSigMouseClicked
        INAH02001a a = new INAH02001a();
        a.setVisible(true);
        INAH02001 i = new INAH02001();
        i.setVisible(false);
    }//GEN-LAST:event_lblSigMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INAH02001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INAH02001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INAH02001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INAH02001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INAH02001().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SolicitudParaAutorizacionDe;
    private javax.swing.ButtonGroup TipoDeInmueble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblSig;
    private javax.swing.JPanel pnlCalle;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlCodigoP;
    private javax.swing.JPanel pnlColonia;
    private javax.swing.JPanel pnlExpediente;
    private javax.swing.JPanel pnlFecha;
    private javax.swing.JPanel pnlHomoclave;
    private javax.swing.JPanel pnlLocalidad;
    private javax.swing.JPanel pnlMunicipio;
    private javax.swing.JPanel pnlNumExt;
    private javax.swing.JPanel pnlNumInt;
    private javax.swing.JPanel pnlSolicitudAutorizacion;
    private javax.swing.JPanel pnlTipoInmueble;
    private javax.swing.JPanel pnlUbicacionDel;
    private javax.swing.JPanel pnlVentanilla;
    private javax.swing.JPanel pnlZonaDe;
    private javax.swing.JRadioButton rbAnuncio;
    private javax.swing.JRadioButton rbColindante;
    private javax.swing.JRadioButton rbMonumento;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.JRadioButton rbToldo;
    private javax.swing.JRadioButton rbZona;
    private javax.swing.JRadioButton rdAntena;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCentro;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtExpediente;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHomoclave;
    private javax.swing.JTextField txtLocalidad;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNumExt;
    private javax.swing.JTextField txtNumInt;
    private javax.swing.JTextField txtVentanilla;
    private javax.swing.JTextField txtZonaDeMunicipios;
    // End of variables declaration//GEN-END:variables
}
