/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sinahmax;

import java.awt.Color;

/**
 *
 * @author chiva
 */
public class INAH02001a extends javax.swing.JFrame {

    /**
     * Creates new form INAH02001
     */
    public INAH02001a() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SolicitudParaAutorizacionDe = new javax.swing.ButtonGroup();
        TipoDeInmueble = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlHomoclave = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblInformacion = new javax.swing.JLabel();
        lblReg = new javax.swing.JLabel();
        lblSig = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpDatosDeObra = new javax.swing.JTextPane();
        pnlCodigoP = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtLargo = new javax.swing.JTextField();
        pnlUbicacionDel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnlUbicacionDel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pnlUbicacionDel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pnlCodigoP1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtAlto = new javax.swing.JTextField();
        pnlCodigoP2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtLargo1 = new javax.swing.JTextField();
        pnlCodigoP3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtAlto1 = new javax.swing.JTextField();
        pnlCodigoP4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtEstrucutura = new javax.swing.JTextField();
        pnlCodigoP5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtCubierta = new javax.swing.JTextField();
        pnlCodigoP6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtFondo = new javax.swing.JTextField();
        pnlCodigoP7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtLetras = new javax.swing.JTextField();
        pnlHomoclave1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtLugarYForma = new javax.swing.JTextField();
        pnlHomoclave2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtSistemaIluminacion = new javax.swing.JTextField();
        pnlHomoclave3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtAlturaSobreBanqueta = new javax.swing.JTextField();
        pnlHomoclave4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtTexto = new javax.swing.JTextField();
        pnlHomoclave5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtIdiomaOJustificacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("históricos, INAH-02-001");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 430, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Autorización para colocar anuncios, toldos y/o");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("antenas en monumentos históricos, en inmuebles");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 430, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setText("colindantes con estos o en zona de monumentos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 430, 30));

        pnlHomoclave.setBackground(new java.awt.Color(57, 60, 62));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Datos de la obra solicitada");

        javax.swing.GroupLayout pnlHomoclaveLayout = new javax.swing.GroupLayout(pnlHomoclave);
        pnlHomoclave.setLayout(pnlHomoclaveLayout);
        pnlHomoclaveLayout.setHorizontalGroup(
            pnlHomoclaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        pnlHomoclaveLayout.setVerticalGroup(
            pnlHomoclaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHomoclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 410, 30));

        lblInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ayuda.png"))); // NOI18N
        getContentPane().add(lblInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, -1, -1));

        lblReg.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblReg.setText("<");
        lblReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegMouseClicked(evt);
            }
        });
        getContentPane().add(lblReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, -1, -1));

        lblSig.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblSig.setText(">");
        getContentPane().add(lblSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, -1, -1));

        txpDatosDeObra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        jScrollPane1.setViewportView(txpDatosDeObra);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 410, 110));

        pnlCodigoP.setBackground(new java.awt.Color(57, 60, 62));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Largo;");

        javax.swing.GroupLayout pnlCodigoPLayout = new javax.swing.GroupLayout(pnlCodigoP);
        pnlCodigoP.setLayout(pnlCodigoPLayout);
        pnlCodigoPLayout.setHorizontalGroup(
            pnlCodigoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        pnlCodigoPLayout.setVerticalGroup(
            pnlCodigoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCodigoPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, 30));

        txtLargo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtLargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtLargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 30));

        pnlUbicacionDel.setBackground(new java.awt.Color(57, 60, 62));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Dimensión");

        javax.swing.GroupLayout pnlUbicacionDelLayout = new javax.swing.GroupLayout(pnlUbicacionDel);
        pnlUbicacionDel.setLayout(pnlUbicacionDelLayout);
        pnlUbicacionDelLayout.setHorizontalGroup(
            pnlUbicacionDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUbicacionDelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        );
        pnlUbicacionDelLayout.setVerticalGroup(
            pnlUbicacionDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUbicacionDelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlUbicacionDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 130, 30));

        pnlUbicacionDel1.setBackground(new java.awt.Color(57, 60, 62));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Dimensiones (metros)");

        javax.swing.GroupLayout pnlUbicacionDel1Layout = new javax.swing.GroupLayout(pnlUbicacionDel1);
        pnlUbicacionDel1.setLayout(pnlUbicacionDel1Layout);
        pnlUbicacionDel1Layout.setHorizontalGroup(
            pnlUbicacionDel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlUbicacionDel1Layout.setVerticalGroup(
            pnlUbicacionDel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUbicacionDel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlUbicacionDel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 30));

        pnlUbicacionDel2.setBackground(new java.awt.Color(57, 60, 62));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Materiales");

        javax.swing.GroupLayout pnlUbicacionDel2Layout = new javax.swing.GroupLayout(pnlUbicacionDel2);
        pnlUbicacionDel2.setLayout(pnlUbicacionDel2Layout);
        pnlUbicacionDel2Layout.setHorizontalGroup(
            pnlUbicacionDel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUbicacionDel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlUbicacionDel2Layout.setVerticalGroup(
            pnlUbicacionDel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUbicacionDel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlUbicacionDel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 110, 30));

        pnlCodigoP1.setBackground(new java.awt.Color(57, 60, 62));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Alto:");

        javax.swing.GroupLayout pnlCodigoP1Layout = new javax.swing.GroupLayout(pnlCodigoP1);
        pnlCodigoP1.setLayout(pnlCodigoP1Layout);
        pnlCodigoP1Layout.setHorizontalGroup(
            pnlCodigoP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnlCodigoP1Layout.setVerticalGroup(
            pnlCodigoP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCodigoP1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlCodigoP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 70, 30));

        txtAlto.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtAlto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtAlto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 70, 30));

        pnlCodigoP2.setBackground(new java.awt.Color(57, 60, 62));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Largo;");

        javax.swing.GroupLayout pnlCodigoP2Layout = new javax.swing.GroupLayout(pnlCodigoP2);
        pnlCodigoP2.setLayout(pnlCodigoP2Layout);
        pnlCodigoP2Layout.setHorizontalGroup(
            pnlCodigoP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        pnlCodigoP2Layout.setVerticalGroup(
            pnlCodigoP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCodigoP2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlCodigoP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, 30));

        txtLargo1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtLargo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtLargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 30));

        pnlCodigoP3.setBackground(new java.awt.Color(57, 60, 62));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Alto:");

        javax.swing.GroupLayout pnlCodigoP3Layout = new javax.swing.GroupLayout(pnlCodigoP3);
        pnlCodigoP3.setLayout(pnlCodigoP3Layout);
        pnlCodigoP3Layout.setHorizontalGroup(
            pnlCodigoP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnlCodigoP3Layout.setVerticalGroup(
            pnlCodigoP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCodigoP3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlCodigoP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 70, 30));

        txtAlto1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtAlto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtAlto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 70, 30));

        pnlCodigoP4.setBackground(new java.awt.Color(57, 60, 62));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Estructura:");

        javax.swing.GroupLayout pnlCodigoP4Layout = new javax.swing.GroupLayout(pnlCodigoP4);
        pnlCodigoP4.setLayout(pnlCodigoP4Layout);
        pnlCodigoP4Layout.setHorizontalGroup(
            pnlCodigoP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        pnlCodigoP4Layout.setVerticalGroup(
            pnlCodigoP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCodigoP4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlCodigoP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 60, 30));

        txtEstrucutura.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtEstrucutura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtEstrucutura, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 60, 30));

        pnlCodigoP5.setBackground(new java.awt.Color(57, 60, 62));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Cubierta:");

        javax.swing.GroupLayout pnlCodigoP5Layout = new javax.swing.GroupLayout(pnlCodigoP5);
        pnlCodigoP5.setLayout(pnlCodigoP5Layout);
        pnlCodigoP5Layout.setHorizontalGroup(
            pnlCodigoP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlCodigoP5Layout.setVerticalGroup(
            pnlCodigoP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCodigoP5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlCodigoP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 50, 30));

        txtCubierta.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtCubierta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtCubierta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 50, 30));

        pnlCodigoP6.setBackground(new java.awt.Color(57, 60, 62));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Fondo:");

        javax.swing.GroupLayout pnlCodigoP6Layout = new javax.swing.GroupLayout(pnlCodigoP6);
        pnlCodigoP6.setLayout(pnlCodigoP6Layout);
        pnlCodigoP6Layout.setHorizontalGroup(
            pnlCodigoP6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnlCodigoP6Layout.setVerticalGroup(
            pnlCodigoP6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCodigoP6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlCodigoP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 70, 30));

        txtFondo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 70, 30));

        pnlCodigoP7.setBackground(new java.awt.Color(57, 60, 62));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Letras:");

        javax.swing.GroupLayout pnlCodigoP7Layout = new javax.swing.GroupLayout(pnlCodigoP7);
        pnlCodigoP7.setLayout(pnlCodigoP7Layout);
        pnlCodigoP7Layout.setHorizontalGroup(
            pnlCodigoP7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        pnlCodigoP7Layout.setVerticalGroup(
            pnlCodigoP7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCodigoP7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlCodigoP7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 60, 30));

        txtLetras.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtLetras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 60, 62)));
        getContentPane().add(txtLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 60, 30));

        pnlHomoclave1.setBackground(new java.awt.Color(57, 60, 62));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Lugar y forma de instalación");

        javax.swing.GroupLayout pnlHomoclave1Layout = new javax.swing.GroupLayout(pnlHomoclave1);
        pnlHomoclave1.setLayout(pnlHomoclave1Layout);
        pnlHomoclave1Layout.setHorizontalGroup(
            pnlHomoclave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        pnlHomoclave1Layout.setVerticalGroup(
            pnlHomoclave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHomoclave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 410, 30));

        txtLugarYForma.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtLugarYForma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLugarYForma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtLugarYForma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 410, 30));

        pnlHomoclave2.setBackground(new java.awt.Color(57, 60, 62));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sistema de iluminacion");

        javax.swing.GroupLayout pnlHomoclave2Layout = new javax.swing.GroupLayout(pnlHomoclave2);
        pnlHomoclave2.setLayout(pnlHomoclave2Layout);
        pnlHomoclave2Layout.setHorizontalGroup(
            pnlHomoclave2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlHomoclave2Layout.setVerticalGroup(
            pnlHomoclave2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHomoclave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 200, 30));

        txtSistemaIluminacion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtSistemaIluminacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSistemaIluminacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtSistemaIluminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 200, 30));

        pnlHomoclave3.setBackground(new java.awt.Color(57, 60, 62));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Altura sobre banqueta (metros)");

        javax.swing.GroupLayout pnlHomoclave3Layout = new javax.swing.GroupLayout(pnlHomoclave3);
        pnlHomoclave3.setLayout(pnlHomoclave3Layout);
        pnlHomoclave3Layout.setHorizontalGroup(
            pnlHomoclave3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlHomoclave3Layout.setVerticalGroup(
            pnlHomoclave3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHomoclave3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 200, 30));

        txtAlturaSobreBanqueta.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtAlturaSobreBanqueta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAlturaSobreBanqueta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtAlturaSobreBanqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 200, 30));

        pnlHomoclave4.setBackground(new java.awt.Color(57, 60, 62));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Texto");

        javax.swing.GroupLayout pnlHomoclave4Layout = new javax.swing.GroupLayout(pnlHomoclave4);
        pnlHomoclave4.setLayout(pnlHomoclave4Layout);
        pnlHomoclave4Layout.setHorizontalGroup(
            pnlHomoclave4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        pnlHomoclave4Layout.setVerticalGroup(
            pnlHomoclave4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHomoclave4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 410, 30));

        txtTexto.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtTexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTexto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 410, 40));

        pnlHomoclave5.setBackground(new java.awt.Color(57, 60, 62));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Idioma o justificación");

        javax.swing.GroupLayout pnlHomoclave5Layout = new javax.swing.GroupLayout(pnlHomoclave5);
        pnlHomoclave5.setLayout(pnlHomoclave5Layout);
        pnlHomoclave5Layout.setHorizontalGroup(
            pnlHomoclave5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        pnlHomoclave5Layout.setVerticalGroup(
            pnlHomoclave5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHomoclave5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 410, 30));

        txtIdiomaOJustificacion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtIdiomaOJustificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdiomaOJustificacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtIdiomaOJustificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 410, 30));

        setSize(new java.awt.Dimension(450, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMouseClicked
        INAH02001 i = new INAH02001();
        i.setVisible(true);
        INAH02001a a = new INAH02001a();
        a.setVisible(false);
    }//GEN-LAST:event_lblRegMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INAH02001a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INAH02001a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INAH02001a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INAH02001a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INAH02001a().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SolicitudParaAutorizacionDe;
    private javax.swing.ButtonGroup TipoDeInmueble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblSig;
    private javax.swing.JPanel pnlCodigoP;
    private javax.swing.JPanel pnlCodigoP1;
    private javax.swing.JPanel pnlCodigoP2;
    private javax.swing.JPanel pnlCodigoP3;
    private javax.swing.JPanel pnlCodigoP4;
    private javax.swing.JPanel pnlCodigoP5;
    private javax.swing.JPanel pnlCodigoP6;
    private javax.swing.JPanel pnlCodigoP7;
    private javax.swing.JPanel pnlHomoclave;
    private javax.swing.JPanel pnlHomoclave1;
    private javax.swing.JPanel pnlHomoclave2;
    private javax.swing.JPanel pnlHomoclave3;
    private javax.swing.JPanel pnlHomoclave4;
    private javax.swing.JPanel pnlHomoclave5;
    private javax.swing.JPanel pnlUbicacionDel;
    private javax.swing.JPanel pnlUbicacionDel1;
    private javax.swing.JPanel pnlUbicacionDel2;
    private javax.swing.JTextPane txpDatosDeObra;
    private javax.swing.JTextField txtAlto;
    private javax.swing.JTextField txtAlto1;
    private javax.swing.JTextField txtAlturaSobreBanqueta;
    private javax.swing.JTextField txtCubierta;
    private javax.swing.JTextField txtEstrucutura;
    private javax.swing.JTextField txtFondo;
    private javax.swing.JTextField txtIdiomaOJustificacion;
    private javax.swing.JTextField txtLargo;
    private javax.swing.JTextField txtLargo1;
    private javax.swing.JTextField txtLetras;
    private javax.swing.JTextField txtLugarYForma;
    private javax.swing.JTextField txtSistemaIluminacion;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
