/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sinahmax;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author chiva
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        lblRegEmp.setVisible(false);
        lblVisEmp.setVisible(false);
        lblModEmp.setVisible(false);
        lblElimEmp.setVisible(false);
        lblReg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblRegTram = new javax.swing.JLabel();
        lblTramEst = new javax.swing.JLabel();
        lblMonHis = new javax.swing.JLabel();
        lblModTram = new javax.swing.JLabel();
        lblGenRep = new javax.swing.JLabel();
        lblSig = new javax.swing.JLabel();
        lblRegEmp = new javax.swing.JLabel();
        lblVisEmp = new javax.swing.JLabel();
        lblModEmp = new javax.swing.JLabel();
        lblElimEmp = new javax.swing.JLabel();
        lblReg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        lblRegTram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RegTram.png"))); // NOI18N
        lblRegTram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegTramMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegTram, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        lblTramEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VerTram.png"))); // NOI18N
        getContentPane().add(lblTramEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        lblMonHis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MonHis.png"))); // NOI18N
        getContentPane().add(lblMonHis, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        lblModTram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ModTram.png"))); // NOI18N
        getContentPane().add(lblModTram, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        lblGenRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GenRep.png"))); // NOI18N
        getContentPane().add(lblGenRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        lblSig.setText("--------->");
        lblSig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSigMouseClicked(evt);
            }
        });
        getContentPane().add(lblSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        lblRegEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RegEmp.png"))); // NOI18N
        lblRegEmp.setEnabled(false);
        getContentPane().add(lblRegEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        lblVisEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VisEmp.png"))); // NOI18N
        lblVisEmp.setEnabled(false);
        getContentPane().add(lblVisEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        lblModEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ModEmp.png"))); // NOI18N
        lblModEmp.setEnabled(false);
        getContentPane().add(lblModEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        lblElimEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ElimEmp.png"))); // NOI18N
        lblElimEmp.setEnabled(false);
        getContentPane().add(lblElimEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        lblReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reg.png"))); // NOI18N
        lblReg.setEnabled(false);
        lblReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegMouseClicked(evt);
            }
        });
        getContentPane().add(lblReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        setSize(new java.awt.Dimension(700, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int salir = JOptionPane.showConfirmDialog(null, "¿Seguro que desea cerrar su sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);
        if (salir == JOptionPane.YES_OPTION){
            dispose();
            Bienvenidos m = new Bienvenidos();
            m.setVisible(true); 
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lblSigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSigMouseClicked
        lblRegTram.setVisible(false);
        lblTramEst.setVisible(false);
        lblMonHis.setVisible(false);
        lblModTram.setVisible(false);
        lblGenRep.setVisible(false);
        lblSig.setVisible(false);
        
        lblRegEmp.setVisible(true);
        lblVisEmp.setVisible(true);
        lblModEmp.setVisible(true);
        lblElimEmp.setVisible(true);
        lblReg.setVisible(true);
        
        
        lblRegTram.setEnabled(false);
        lblTramEst.setEnabled(false);
        lblMonHis.setEnabled(false);
        lblModTram.setEnabled(false);
        lblGenRep.setEnabled(false);
        lblSig.setEnabled(false);
        
        lblRegEmp.setEnabled(true);
        lblVisEmp.setEnabled(true);
        lblModEmp.setEnabled(true);
        lblElimEmp.setEnabled(true);
        lblReg.setEnabled(true);
    }//GEN-LAST:event_lblSigMouseClicked

    private void lblRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMouseClicked
        lblRegTram.setVisible(true);
        lblTramEst.setVisible(true);
        lblMonHis.setVisible(true);
        lblModTram.setVisible(true);
        lblGenRep.setVisible(true);
        lblSig.setVisible(true);
        
        lblRegEmp.setVisible(false);
        lblVisEmp.setVisible(false);
        lblModEmp.setVisible(false);
        lblElimEmp.setVisible(false);
        lblReg.setVisible(false);
        
        
        lblRegTram.setEnabled(true);
        lblTramEst.setEnabled(true);
        lblMonHis.setEnabled(true);
        lblModTram.setEnabled(true);
        lblGenRep.setEnabled(true);
        lblSig.setEnabled(true);
        
        lblRegEmp.setEnabled(false);
        lblVisEmp.setEnabled(false);
        lblModEmp.setEnabled(false);
        lblElimEmp.setEnabled(false);
        lblReg.setEnabled(false);
    }//GEN-LAST:event_lblRegMouseClicked

    private void lblRegTramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegTramMouseClicked
        dispose();
        RegTram r = new RegTram();
        r.setVisible(true);
    }//GEN-LAST:event_lblRegTramMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblElimEmp;
    private javax.swing.JLabel lblGenRep;
    private javax.swing.JLabel lblModEmp;
    private javax.swing.JLabel lblModTram;
    private javax.swing.JLabel lblMonHis;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblRegEmp;
    private javax.swing.JLabel lblRegTram;
    private javax.swing.JLabel lblSig;
    private javax.swing.JLabel lblTramEst;
    private javax.swing.JLabel lblVisEmp;
    // End of variables declaration//GEN-END:variables
}
